databases:
  - name: dupecord
    user: cubeydice
    plan: free
    region: oregon

services:
  - type: web
    name: dupecord
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: dupecord
        property: connectionString
    - key: RAILS_MASTER_KEY
        sync: false
